@Ekid.Api_HostAddress = http://localhost:5185

### Create activity
POST {{Ekid.Api_HostAddress}}/api/activities
Content-Type: application/json

{
  "description": "something",
  "type": "Diagnosis",
  "duration": 45,
  "price": 120
}

> {% client.global.set("activityId", response.body); %}

### Get activity
GET {{Ekid.Api_HostAddress}}/api/activities/{{activityId}}

### Get all activities
GET {{Ekid.Api_HostAddress}}/api/activities
