### Sign In User
POST {{baseUrl}}/identity/user/login
Content-Type: application/json

{
  "email": "email@superadmin.com",
  "password": "P@sw0rd"
}

> {% client.global.set("accessToken", response.body.accessToken); %}